//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotesMarketplaceEntities : DbContext
    {
        public NotesMarketplaceEntities()
            : base("name=NotesMarketplaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminProfile> AdminProfiles { get; set; }
        public virtual DbSet<CTC> CTCs { get; set; }
        public virtual DbSet<DownloadedNote> DownloadedNotes { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<ManageCTC> ManageCTCs { get; set; }
        public virtual DbSet<NotesDetail> NotesDetails { get; set; }
        public virtual DbSet<NotesStatu> NotesStatus { get; set; }
        public virtual DbSet<SpamReport> SpamReports { get; set; }
        public virtual DbSet<Statistic> Statistics { get; set; }
        public virtual DbSet<SystemConfiguration> SystemConfigurations { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
