//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class NotesDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotesDetail()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.SpamReports = new HashSet<SpamReport>();
        }

        public int P_K_Note { get; set; }

        [Required]
        public int F_K_User { get; set; }

        public int F_K_NoteStatus { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Category { get; set; }

        public String BookPicture { get; set; }

        public string NoteAttachment { get; set; }
        public string NoteType { get; set; }

        [RegularExpression("^[0-9]*$", ErrorMessage = "Enter valid number")]
        public Nullable<int> NumberOfPages { get; set; }

        public HttpPostedFileBase Book_Picture { get; set; }
        public HttpPostedFileBase Note_Attachment { get; set; }
        public HttpPostedFileBase Note_Preview { get; set; }

        [Required]
        public string NotesDescription { get; set; }
        public string InstitutionName { get; set; }
        public string Country { get; set; }
        public string Course { get; set; }
        public string CourseCode { get; set; }
        public string Professor { get; set; }

        [Required]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Enter valid price")]
        public int SellPrice { get; set; }
        public string NotePreview { get; set; }
        public Nullable<int> NoteSize { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual NotesStatu NotesStatu { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpamReport> SpamReports { get; set; }
    }
}
