//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int ID { get; set; }
        public int F_K_User { get; set; }
        public int UnderReviewNotes { get; set; }
        public int PublishedNotes { get; set; }
        public int DownloadedNotes { get; set; }
        public int TotalExpensis { get; set; }
        public int TotalEarning { get; set; }
        public int BuyerRequests { get; set; }
        public int SoldNotes { get; set; }
        public int RejectedNotes { get; set; }
    
        public virtual User User { get; set; }
    }
}
